FROM python:3.7-slim-buster

# Instalacion de las dependencias de software 
RUN apt-get update && apt-get install build-essential -y --no-install-recommends && apt-get install nano -y --no-install-recommends 
