version: '3.4'

services:

  # information dispersal algorithm
  ida1-s10: 
    image: 127.0.0.1:5000/ida:ida-m-s10
    build:
      context: ../.././
    tty: true
    entrypoint: ["python", "run.py", "-r", "10000"]
    restart: "no"
    environment:
      SOL_ID: ${SOL_ID:-1}
      W_ID: 1
  ida2-s10: 
    image: 127.0.0.1:5000/ida:ida-m-s10
    build:
      context: ../.././
    tty: true
    entrypoint: ["python", "run.py", "-r", "10000"]
    restart: "no"
    environment:
      SOL_ID: ${SOL_ID:-1}
      W_ID: 2
  ida3-s10: 
    image: 127.0.0.1:5000/ida:ida-m-s10
    build:
      context: ../.././
    tty: true
    entrypoint: ["python", "run.py", "-r", "10000"]
    restart: "no"
    environment:
      SOL_ID: ${SOL_ID:-1}
      W_ID: 3
  ida4-s10: 
    image: 127.0.0.1:5000/ida:ida-m-s10
    build:
      context: ../.././
    tty: true
    entrypoint: ["python", "run.py", "-r", "10000"]
    restart: "no"
    environment:
      SOL_ID: ${SOL_ID:-1}
      W_ID: 4
  ida5-s10: 
    image: 127.0.0.1:5000/ida:ida-m-s10
    build:
      context: ../.././
    tty: true
    entrypoint: ["python", "run.py", "-r", "10000"]
    restart: "no"
    environment:
      SOL_ID: ${SOL_ID:-1}
      W_ID: 5
  ida6-s10: 
    image: 127.0.0.1:5000/ida:ida-m-s10
    build:
      context: ../.././
    tty: true
    entrypoint: ["python", "run.py", "-r", "10000"]
    restart: "no"
    environment:
      SOL_ID: ${SOL_ID:-1}
      W_ID: 6
  ida7-s10: 
    image: 127.0.0.1:5000/ida:ida-m-s10
    build:
      context: ../.././
    tty: true
    entrypoint: ["python", "run.py", "-r", "10000"]
    restart: "no"
    environment:
      SOL_ID: ${SOL_ID:-1}
      W_ID: 7
  ida8-s10: 
    image: 127.0.0.1:5000/ida:ida-m-s10
    build:
      context: ../.././
    tty: true
    entrypoint: ["python", "run.py", "-r", "10000"]
    restart: "no"
    environment:
      SOL_ID: ${SOL_ID:-1}
      W_ID: 8
  ida9-s10: 
    image: 127.0.0.1:5000/ida:ida-m-s10
    build:
      context: ../.././
    tty: true
    entrypoint: ["python", "run.py", "-r", "10000"]
    restart: "no"
    environment:
      SOL_ID: ${SOL_ID:-1}
      W_ID: 9
  ida10-s10: 
    image: 127.0.0.1:5000/ida:ida-m-s10
    build:
      context: ../.././
    tty: true
    entrypoint: ["python", "run.py", "-r", "10000"]
    restart: "no"
    environment:
      SOL_ID: ${SOL_ID:-1}
      W_ID: 10


x-model-solution:
  title: sol1c10
  description: Test with one container
  structure:
    - ida1-s10->ida1-s10
    - ida2-s10->ida2-s10
    - ida3-s10->ida3-s10
    - ida4-s10->ida4-s10
    - ida5-s10->ida5-s10
    - ida6-s10->ida6-s10
    - ida7-s10->ida7-s10
    - ida8-s10->ida8-s10
    - ida9-s10->ida9-s10
    - ida10-s10->ida10-s10
  x-services:
    ida1-s10:
      description: Information Dispersal Algorithm
      input:
        description: Shows the input of the Thing
        elements:
          - n: 8
          - m: 4
          - field: 8
          - folder: input/
      output:
        description: Shows the output of the Thing
        elements:
          - folder: output/
      functions:
        Dis: 
          - Disperse a file in n chunks
          - https://myida.example.com/Dis
        Rec: 
          - Recover a file by its m chunks
          - https://myida.example.com/Rec
    ida2-s10:
      description: Information Dispersal Algorithm
      input:
        description: Shows the input of the Thing
        elements:
          - n: 8
          - m: 4
          - field: 8
          - folder: input/
      output:
        description: Shows the output of the Thing
        elements:
          - folder: output/
      functions:
        Dis: 
          - Disperse a file in n chunks
          - https://myida.example.com/Dis
        Rec: 
          - Recover a file by its m chunks
          - https://myida.example.com/Rec
    ida3-s10:
      description: Information Dispersal Algorithm
      input:
        description: Shows the input of the Thing
        elements:
          - n: 8
          - m: 4
          - field: 8
          - folder: input/
      output:
        description: Shows the output of the Thing
        elements:
          - folder: output/
      functions:
        Dis: 
          - Disperse a file in n chunks
          - https://myida.example.com/Dis
        Rec: 
          - Recover a file by its m chunks
          - https://myida.example.com/Rec
    ida4-s10:
      description: Information Dispersal Algorithm
      input:
        description: Shows the input of the Thing
        elements:
          - n: 8
          - m: 4
          - field: 8
          - folder: input/
      output:
        description: Shows the output of the Thing
        elements:
          - folder: output/
      functions:
        Dis: 
          - Disperse a file in n chunks
          - https://myida.example.com/Dis
        Rec: 
          - Recover a file by its m chunks
          - https://myida.example.com/Rec
    ida5-s10:
      description: Information Dispersal Algorithm
      input:
        description: Shows the input of the Thing
        elements:
          - n: 8
          - m: 4
          - field: 8
          - folder: input/
      output:
        description: Shows the output of the Thing
        elements:
          - folder: output/
      functions:
        Dis: 
          - Disperse a file in n chunks
          - https://myida.example.com/Dis
        Rec: 
          - Recover a file by its m chunks
          - https://myida.example.com/Rec
    ida6-s10:
      description: Information Dispersal Algorithm
      input:
        description: Shows the input of the Thing
        elements:
          - n: 8
          - m: 4
          - field: 8
          - folder: input/
      output:
        description: Shows the output of the Thing
        elements:
          - folder: output/
      functions:
        Dis: 
          - Disperse a file in n chunks
          - https://myida.example.com/Dis
        Rec: 
          - Recover a file by its m chunks
          - https://myida.example.com/Rec
    ida7-s10:
      description: Information Dispersal Algorithm
      input:
        description: Shows the input of the Thing
        elements:
          - n: 8
          - m: 4
          - field: 8
          - folder: input/
      output:
        description: Shows the output of the Thing
        elements:
          - folder: output/
      functions:
        Dis: 
          - Disperse a file in n chunks
          - https://myida.example.com/Dis
        Rec: 
          - Recover a file by its m chunks
          - https://myida.example.com/Rec
    ida8-s10:
      description: Information Dispersal Algorithm
      input:
        description: Shows the input of the Thing
        elements:
          - n: 8
          - m: 4
          - field: 8
          - folder: input/
      output:
        description: Shows the output of the Thing
        elements:
          - folder: output/
      functions:
        Dis: 
          - Disperse a file in n chunks
          - https://myida.example.com/Dis
        Rec: 
          - Recover a file by its m chunks
          - https://myida.example.com/Rec
    ida9-s10:
      description: Information Dispersal Algorithm
      input:
        description: Shows the input of the Thing
        elements:
          - n: 8
          - m: 4
          - field: 8
          - folder: input/
      output:
        description: Shows the output of the Thing
        elements:
          - folder: output/
      functions:
        Dis: 
          - Disperse a file in n chunks
          - https://myida.example.com/Dis
        Rec: 
          - Recover a file by its m chunks
          - https://myida.example.com/Rec
    ida10-s10:
      description: Information Dispersal Algorithm
      input:
        description: Shows the input of the Thing
        elements:
          - n: 8
          - m: 4
          - field: 8
          - folder: input/
      output:
        description: Shows the output of the Thing
        elements:
          - folder: output/
      functions:
        Dis: 
          - Disperse a file in n chunks
          - https://myida.example.com/Dis
        Rec: 
          - Recover a file by its m chunks
          - https://myida.example.com/Rec
