version: '3.4'

services:

  # information dispersal algorithm
  s6ida1: 
    image: fbalderas/ida:ida-m-s6
    build:
      dockerfile: s10/c10/6/Dockerfile-s6
      context: ../../.././
    tty: true
    entrypoint: ["python", "run.py", "-r", "10000"]
    restart: "no"
    environment:
      SOL_ID: ${SOL_ID:-1}
      W_ID: 1
  s6ida2: 
    image: fbalderas/ida:ida-m-s6
    build:
      dockerfile: s10/c10/6/Dockerfile-s6
      context: ../../.././
    tty: true
    entrypoint: ["python", "run.py", "-r", "10000"]
    restart: "no"
    environment:
      SOL_ID: ${SOL_ID:-1}
      W_ID: 2
  s6ida3: 
    image: fbalderas/ida:ida-m-s6
    build:
      dockerfile: s10/c10/6/Dockerfile-s6
      context: ../../.././
    tty: true
    entrypoint: ["python", "run.py", "-r", "10000"]
    restart: "no"
    environment:
      SOL_ID: ${SOL_ID:-1}
      W_ID: 3
  s6ida4: 
    image: fbalderas/ida:ida-m-s6
    build:
      dockerfile: s10/c10/6/Dockerfile-s6
      context: ../../.././
    tty: true
    entrypoint: ["python", "run.py", "-r", "10000"]
    restart: "no"
    environment:
      SOL_ID: ${SOL_ID:-1}
      W_ID: 4
  s6ida5: 
    image: fbalderas/ida:ida-m-s6
    build:
      dockerfile: s10/c10/6/Dockerfile-s6
      context: ../../.././
    tty: true
    entrypoint: ["python", "run.py", "-r", "10000"]
    restart: "no"
    environment:
      SOL_ID: ${SOL_ID:-1}
      W_ID: 5
  s6ida6: 
    image: fbalderas/ida:ida-m-s6
    build:
      dockerfile: s10/c10/6/Dockerfile-s6
      context: ../../.././
    tty: true
    entrypoint: ["python", "run.py", "-r", "10000"]
    restart: "no"
    environment:
      SOL_ID: ${SOL_ID:-1}
      W_ID: 6
  s6ida7: 
    image: fbalderas/ida:ida-m-s6
    build:
      dockerfile: s10/c10/6/Dockerfile-s6
      context: ../../.././
    tty: true
    entrypoint: ["python", "run.py", "-r", "10000"]
    restart: "no"
    environment:
      SOL_ID: ${SOL_ID:-1}
      W_ID: 7
  s6ida8: 
    image: fbalderas/ida:ida-m-s6
    build:
      dockerfile: s10/c10/6/Dockerfile-s6
      context: ../../.././
    tty: true
    entrypoint: ["python", "run.py", "-r", "10000"]
    restart: "no"
    environment:
      SOL_ID: ${SOL_ID:-1}
      W_ID: 8
  s6ida9: 
    image: fbalderas/ida:ida-m-s6
    build:
      dockerfile: s10/c10/6/Dockerfile-s6
      context: ../../.././
    tty: true
    entrypoint: ["python", "run.py", "-r", "10000"]
    restart: "no"
    environment:
      SOL_ID: ${SOL_ID:-1}
      W_ID: 9
  s6ida10: 
    image: fbalderas/ida:ida-m-s6
    build:
      dockerfile: s10/c10/6/Dockerfile-s6
      context: ../../.././
    tty: true
    entrypoint: ["python", "run.py", "-r", "10000"]
    restart: "no"
    environment:
      SOL_ID: ${SOL_ID:-1}
      W_ID: 10


x-model-solution:
  title: sol6c10
  description: Test with one container
  structure:
    - s6ida1->s6ida1
    - s6ida2->s6ida2
    - s6ida3->s6ida3
    - s6ida4->s6ida4
    - s6ida5->s6ida5
    - s6ida6->s6ida6
    - s6ida7->s6ida7
    - s6ida8->s6ida8
    - s6ida9->s6ida9
    - s6ida10->s6ida10
  x-services:
    s6ida1:
      description: Information Dispersal Algorithm
      input:
        description: Shows the input of the Thing
        elements:
          - n: 8
          - m: 4
          - field: 8
          - folder: input/
      output:
        description: Shows the output of the Thing
        elements:
          - folder: output/
      functions:
        Dis: 
          - Disperse a file in n chunks
          - https://myida.example.com/Dis
        Rec: 
          - Recover a file by its m chunks
          - https://myida.example.com/Rec
    s6ida2:
      description: Information Dispersal Algorithm
      input:
        description: Shows the input of the Thing
        elements:
          - n: 8
          - m: 4
          - field: 8
          - folder: input/
      output:
        description: Shows the output of the Thing
        elements:
          - folder: output/
      functions:
        Dis: 
          - Disperse a file in n chunks
          - https://myida.example.com/Dis
        Rec: 
          - Recover a file by its m chunks
          - https://myida.example.com/Rec
    s6ida3:
      description: Information Dispersal Algorithm
      input:
        description: Shows the input of the Thing
        elements:
          - n: 8
          - m: 4
          - field: 8
          - folder: input/
      output:
        description: Shows the output of the Thing
        elements:
          - folder: output/
      functions:
        Dis: 
          - Disperse a file in n chunks
          - https://myida.example.com/Dis
        Rec: 
          - Recover a file by its m chunks
          - https://myida.example.com/Rec
    s6ida4:
      description: Information Dispersal Algorithm
      input:
        description: Shows the input of the Thing
        elements:
          - n: 8
          - m: 4
          - field: 8
          - folder: input/
      output:
        description: Shows the output of the Thing
        elements:
          - folder: output/
      functions:
        Dis: 
          - Disperse a file in n chunks
          - https://myida.example.com/Dis
        Rec: 
          - Recover a file by its m chunks
          - https://myida.example.com/Rec
    s6ida5:
      description: Information Dispersal Algorithm
      input:
        description: Shows the input of the Thing
        elements:
          - n: 8
          - m: 4
          - field: 8
          - folder: input/
      output:
        description: Shows the output of the Thing
        elements:
          - folder: output/
      functions:
        Dis: 
          - Disperse a file in n chunks
          - https://myida.example.com/Dis
        Rec: 
          - Recover a file by its m chunks
          - https://myida.example.com/Rec
    s6ida6:
      description: Information Dispersal Algorithm
      input:
        description: Shows the input of the Thing
        elements:
          - n: 8
          - m: 4
          - field: 8
          - folder: input/
      output:
        description: Shows the output of the Thing
        elements:
          - folder: output/
      functions:
        Dis: 
          - Disperse a file in n chunks
          - https://myida.example.com/Dis
        Rec: 
          - Recover a file by its m chunks
          - https://myida.example.com/Rec
    s6ida7:
      description: Information Dispersal Algorithm
      input:
        description: Shows the input of the Thing
        elements:
          - n: 8
          - m: 4
          - field: 8
          - folder: input/
      output:
        description: Shows the output of the Thing
        elements:
          - folder: output/
      functions:
        Dis: 
          - Disperse a file in n chunks
          - https://myida.example.com/Dis
        Rec: 
          - Recover a file by its m chunks
          - https://myida.example.com/Rec
    s6ida8:
      description: Information Dispersal Algorithm
      input:
        description: Shows the input of the Thing
        elements:
          - n: 8
          - m: 4
          - field: 8
          - folder: input/
      output:
        description: Shows the output of the Thing
        elements:
          - folder: output/
      functions:
        Dis: 
          - Disperse a file in n chunks
          - https://myida.example.com/Dis
        Rec: 
          - Recover a file by its m chunks
          - https://myida.example.com/Rec
    s6ida9:
      description: Information Dispersal Algorithm
      input:
        description: Shows the input of the Thing
        elements:
          - n: 8
          - m: 4
          - field: 8
          - folder: input/
      output:
        description: Shows the output of the Thing
        elements:
          - folder: output/
      functions:
        Dis: 
          - Disperse a file in n chunks
          - https://myida.example.com/Dis
        Rec: 
          - Recover a file by its m chunks
          - https://myida.example.com/Rec
    s6ida10:
      description: Information Dispersal Algorithm
      input:
        description: Shows the input of the Thing
        elements:
          - n: 8
          - m: 4
          - field: 8
          - folder: input/
      output:
        description: Shows the output of the Thing
        elements:
          - folder: output/
      functions:
        Dis: 
          - Disperse a file in n chunks
          - https://myida.example.com/Dis
        Rec: 
          - Recover a file by its m chunks
          - https://myida.example.com/Rec
