version: '3'
services:
  dagsink_mongodb: #mongoDB
    image: mongo:latest
    restart: always
    environment:
      dagsink-db-volume: /data/db
    volumes:
      - dagsink-db-volume:/data/db
    #ports:
      #- 33000:27017
  dagsink: #mongoDB
    image: dagsink
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    environment:
      MONGO_DB: dagsink_mongodb
    ports:
      - 9800:9800

volumes:
  dagsink-db-volume:
